repos:
  - repo: local
    hooks:
      - id: generate-wavelet-compile-db
        name: Generate tt-wavelet compile database
        entry: bash ./scripts/generate_compile_db.sh
        language: system
        pass_filenames: false
        files: ^tt-wavelet/.*\.(c|cc|cpp|cxx|h|hpp)$

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]
        exclude: (^|/)tt-metal/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]
        exclude: (^|/)tt-metal/

  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.1.12
    hooks:
      - id: clang-format
        args: [--style=file, --version=20]
        files: ^tt-wavelet/.*\.(c|cc|cpp|cxx|h|hpp)$
      - id: clang-tidy
        args: [-p=build/ci-clang-tidy, --config-file=.clang-tidy, --version=20]
        files: ^tt-wavelet/.*\.(c|cc|cpp|cxx|h|hpp)$
